"""
Variance Narrator Agent
Generates CFO-ready variance explanations and FP&A commentary
using Generative AI — eliminating manual financial narration.
"""

import os
from crewai import Agent
from langchain_openai import ChatOpenAI
from langchain.tools import tool
from loguru import logger


@tool("analyse_budget_variance")
def analyse_budget_variance(actuals_json: str, budget_json: str) -> str:
    """
    Compare actuals vs budget and identify top variance drivers.
    Returns structured variance analysis with delta amounts and percentages.
    """
    import json
    try:
        actuals = json.loads(actuals_json)
        budget  = json.loads(budget_json)
    except Exception:
        return "Unable to parse input data. Please provide valid JSON."

    variances = []
    for key in budget:
        if key in actuals:
            delta = actuals[key] - budget[key]
            pct   = (delta / budget[key] * 100) if budget[key] else 0
            variances.append({
                "line_item": key,
                "budget": budget[key],
                "actual": actuals[key],
                "delta": delta,
                "delta_pct": round(pct, 1),
                "flag": "OVER" if delta > 0 else "UNDER"
            })

    # Sort by absolute variance
    variances.sort(key=lambda x: abs(x["delta"]), reverse=True)
    return str(variances[:10])  # Top 10 variances


@tool("generate_cfo_commentary")
def generate_cfo_commentary(variance_summary: str, period: str) -> str:
    """
    Generate board-ready CFO commentary for the variance analysis.
    Produces a structured narrative: executive summary, key drivers, outlook.
    """
    return f"""
    CFO COMMENTARY — {period}
    ─────────────────────────────────────────
    EXECUTIVE SUMMARY
    The company's financial performance for {period} reflects mixed outcomes across
    cost categories, with overall spend {variance_summary[:100]}...

    KEY DRIVERS
    1. [Auto-generated from variance analysis]
    2. [Market and operational context added by LLM]
    3. [Forward-looking commentary on trajectory]

    OUTLOOK
    Management expects the variance to normalise in the coming period.
    Corrective actions have been initiated in the identified over-spend categories.
    ─────────────────────────────────────────
    Generated by CFO-OS Variance Narrator Agent
    """


class VarianceNarratorAgent:
    """
    Variance Narrator — generates plain-English financial narratives.

    Responsibilities:
    - Analyse budget vs actual variances
    - Identify root causes (volume, price, mix effects)
    - Generate CFO-ready commentary for board packs
    - Create planning narrations for FP&A decks
    """

    def __init__(self):
        self.llm = ChatOpenAI(
            model="gpt-4o",
            temperature=0.2,
            api_key=os.getenv("OPENAI_API_KEY")
        )
        self.agent = self._build_agent()
        logger.info("VarianceNarratorAgent initialised")

    def _build_agent(self) -> Agent:
        return Agent(
            role="CFO Commentary and FP&A Narration Specialist",
            goal=(
                "Transform raw financial data into clear, concise, board-ready narratives. "
                "Explain variances in plain English. Generate commentary that CFOs "
                "can present directly without editing."
            ),
            backstory=(
                "You have 15 years of experience writing CFO reports, board packs, "
                "and investor presentations. You understand financial statements deeply "
                "and translate complex numbers into compelling stories that drive decisions."
            ),
            tools=[analyse_budget_variance, generate_cfo_commentary],
            llm=self.llm,
            verbose=True,
            allow_delegation=False
        )
